--------------------------------------------------------
--  파일이 생성됨 - 일요일-3월-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ADMIN
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_ADMIN"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ASK
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_ASK"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CART
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_CART"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CATEGORY
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_CATEGORY"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_MEMBER"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MYPAGE
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_MYPAGE"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORDERING
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_ORDERING"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORDERINGREVIEW
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_ORDERINGREVIEW"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_PRODUCT"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_QNA
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_QNA"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RECIEVEREVIEW
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_RECIEVEREVIEW"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SELLER
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_SELLER"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_WISHLIST
--------------------------------------------------------

   CREATE SEQUENCE  "C##AMALL"."SEQ_WISHLIST"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN_MEMBER
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."ADMIN_MEMBER" 
   (	"ADMIN_ID" VARCHAR2(20 BYTE), 
	"ADMIN_NAME" VARCHAR2(20 BYTE), 
	"ADMIN_PWD" VARCHAR2(20 BYTE), 
	"ADMIN_EMAIL" VARCHAR2(40 BYTE), 
	"ADMIN_PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."ADMIN_MEMBER" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."ADMIN_MEMBER" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."ADMIN_MEMBER" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."ADMIN_MEMBER" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table ASK
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."ASK" 
   (	"ASK_NUM" NUMBER(5,0), 
	"ASK_TITLE" VARCHAR2(20 BYTE), 
	"ASK_CONTENT" VARCHAR2(400 BYTE), 
	"ASK_DATE" DATE, 
	"ASK_REPLY" VARCHAR2(400 BYTE), 
	"ASK_REPLYEXIST" NUMBER(1,0) DEFAULT 1, 
	"MEMBER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."ASK" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."ASK" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."ASK" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."ASK" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."CART" 
   (	"CART_ID" NUMBER(8,0), 
	"CART_QUANTITY" NUMBER(5,0), 
	"CART_REGDATE" DATE, 
	"CART_RESULT" CHAR(1 BYTE) DEFAULT 1, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"PROD_NUM" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."CART" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."CART" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."CART" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."CART" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."CATEGORY" 
   (	"CATEGORY_ID" NUMBER(5,0), 
	"CATEGORY_NAME" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."CATEGORY" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."CATEGORY" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."CATEGORY" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."CATEGORY" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."MEMBER" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"MEMBER_BIRTH" VARCHAR2(10 BYTE), 
	"MEMBER_PWD" VARCHAR2(20 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(40 BYTE), 
	"MEMBER_PHONE" VARCHAR2(20 BYTE), 
	"MEMBER_SEX" NUMBER(1,0), 
	"MEMBER_REG_DATE" CHAR(18 BYTE), 
	"MEMBER_CONNECT_DATE" CHAR(18 BYTE), 
	"MEMBER_HASH" VARCHAR2(4000 BYTE), 
	"MEMBER_MATCH_ID" VARCHAR2(20 BYTE), 
	"MEMBER_POST_CODE" VARCHAR2(5 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(4000 BYTE), 
	"MEMBER_DETAIL_ADDRESS" VARCHAR2(4000 BYTE), 
	"MEMBER_EXTRA_ADDRESS" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MYPAGE
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."MYPAGE" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_ADDRESS" VARCHAR2(200 BYTE), 
	"MEMBER_YN" NUMBER(1,0) DEFAULT 1, 
	"MATCH_YN" NUMBER(1,0) DEFAULT 1, 
	"RECIEVE_REVIEW_NUM" NUMBER(5,0), 
	"ORDERING_REVIEW_NUM" NUMBER(5,0), 
	"QNA_NUM" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."MYPAGE" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."MYPAGE" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."MYPAGE" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."MYPAGE" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table ORDERING
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."ORDERING" 
   (	"ORDERING_NUM" NUMBER(5,0), 
	"ORDERING_DATE" DATE, 
	"ORDERING_NAME1" VARCHAR2(20 BYTE), 
	"ORDERING_PHONE1" VARCHAR2(20 BYTE), 
	"ORDERING_ADDRESS1" VARCHAR2(200 BYTE), 
	"ORDERING_NAME2" VARCHAR2(20 BYTE), 
	"ORDERING_PHONE2" VARCHAR2(20 BYTE), 
	"ORDERING_ADDRESS2" VARCHAR2(200 BYTE), 
	"ORDERING_QUANTITY" NUMBER(5,0), 
	"ORDERING_CARD" NUMBER(1,0) DEFAULT 1, 
	"ORDERING_LETTER" VARCHAR2(200 BYTE), 
	"ORDERING_REQUEST" VARCHAR2(200 BYTE), 
	"ORDERING_TOTAL" NUMBER(8,0), 
	"ORDERING_RESULT" NUMBER(1,0) DEFAULT 1, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"PROD_NUM" NUMBER(5,0), 
	"CART_ID" NUMBER(8,0), 
	"SELLER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."ORDERING" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."ORDERING" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."ORDERING" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."ORDERING" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table ORDERINGREVIEW
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."ORDERINGREVIEW" 
   (	"ORDERING_REVIEW_NUM" NUMBER(5,0), 
	"ORDERING_REVIEW_WRITER" VARCHAR2(20 BYTE), 
	"ORDERING_REVIEW_PWD" VARCHAR2(20 BYTE), 
	"ORDERING_REVIEW_TITLE" VARCHAR2(100 BYTE), 
	"ORDERING_REVIEW_CONTENT" VARCHAR2(300 BYTE), 
	"ORDERING_REVIEW_IMAGE1" BLOB, 
	"ORDERING_REVIEW_IMAGE2" BLOB, 
	"ORDERING_REVIEW_SHOW" NUMBER(1,0) DEFAULT 1, 
	"PROD_NUM" NUMBER(5,0), 
	"ORDERING_NUM" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ORDERING_REVIEW_IMAGE1") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ORDERING_REVIEW_IMAGE2") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT SELECT ON "C##AMALL"."ORDERINGREVIEW" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."ORDERINGREVIEW" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."ORDERINGREVIEW" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."ORDERINGREVIEW" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."PRODUCT" 
   (	"PROD_NUM" NUMBER(5,0), 
	"PROD_NAME" VARCHAR2(100 BYTE), 
	"PROD_CODE" VARCHAR2(100 BYTE), 
	"PROD_PRICE" NUMBER(10,0), 
	"PROD_STOCK" NUMBER(10,0), 
	"PROD_EXPLANATION" VARCHAR2(1000 BYTE), 
	"PROD_REGDATE" VARCHAR2(10 BYTE), 
	"PROD_HIT" NUMBER(10,0), 
	"PROD_DETAIL" VARCHAR2(2000 BYTE), 
	"PROD_VAL1" CHAR(20 BYTE), 
	"PROD_VAL2" CHAR(20 BYTE), 
	"PROD_VAL3" CHAR(20 BYTE), 
	"PROD_STAR" NUMBER(1,0) DEFAULT 0, 
	"PROD_SHOW" NUMBER(1,0) DEFAULT 1, 
	"SELLER_ID" VARCHAR2(20 BYTE), 
	"CATEGORY_ID" NUMBER(5,0), 
	"PROD_IMAGE1" VARCHAR2(1000 BYTE), 
	"PROD_IMAGE2" VARCHAR2(1000 BYTE), 
	"PROD_IMAGE3" VARCHAR2(1000 BYTE), 
	"PROD_DELIVERYFEE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."PRODUCT" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."PRODUCT" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."PRODUCT" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."PRODUCT" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."QNA" 
   (	"QNA_NUM" NUMBER(5,0), 
	"QNA_TITLE" VARCHAR2(20 BYTE), 
	"QNA_CONTENT" VARCHAR2(400 BYTE), 
	"QNA_DATE" DATE, 
	"QNA_REPLY" VARCHAR2(400 BYTE), 
	"QNA_REPLYEXIST" NUMBER(1,0) DEFAULT 1, 
	"PROD_NUM" NUMBER(5,0), 
	"MEMBER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."QNA" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."QNA" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."QNA" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."QNA" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table RECIEVEREVIEW
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."RECIEVEREVIEW" 
   (	"RECIEVE_REVIEW_NUM" NUMBER(5,0), 
	"ORDERING_NUM" NUMBER(5,0), 
	"PROD_NUM" NUMBER(5,0), 
	"RECIEVE_REVIEW_WRITER" VARCHAR2(20 BYTE), 
	"RECIEVE_REVIEW_PWD" VARCHAR2(20 BYTE), 
	"RECIEVE_REVIEW_TITLE" VARCHAR2(100 BYTE), 
	"RECIEVE_REVIEW_CONTENT" VARCHAR2(300 BYTE), 
	"RECIEVE_REVIEW_IMAGE1" BLOB, 
	"RECIEVE_REVIEW_IMAGE2" BLOB, 
	"RECIEVE_REVIEW_STAR" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("RECIEVE_REVIEW_IMAGE1") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("RECIEVE_REVIEW_IMAGE2") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT SELECT ON "C##AMALL"."RECIEVEREVIEW" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."RECIEVEREVIEW" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."RECIEVEREVIEW" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."RECIEVEREVIEW" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."SELLER" 
   (	"SELLER_ID" VARCHAR2(20 BYTE), 
	"SELLER_PWD" VARCHAR2(20 BYTE), 
	"SELLER_NICKNAME" VARCHAR2(20 BYTE), 
	"SELLER_INTRO" VARCHAR2(1000 BYTE), 
	"SELLER_REVENUE" NUMBER(20,0) DEFAULT 0, 
	"SELLER_IMAGE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."SELLER" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."SELLER" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."SELLER" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."SELLER" TO "C##AMALLL";
--------------------------------------------------------
--  DDL for Table WISHLIST
--------------------------------------------------------

  CREATE TABLE "C##AMALL"."WISHLIST" 
   (	"WISHLIST_ID" NUMBER(8,0), 
	"WISHLIST_SHOW" NUMBER(1,0) DEFAULT 1, 
	"WISHLIST_REGDATE" DATE, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"PROD_NUM" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  GRANT SELECT ON "C##AMALL"."WISHLIST" TO "C##AMALLL";
  GRANT DELETE ON "C##AMALL"."WISHLIST" TO "C##AMALLL";
  GRANT INSERT ON "C##AMALL"."WISHLIST" TO "C##AMALLL";
  GRANT UPDATE ON "C##AMALL"."WISHLIST" TO "C##AMALLL";
REM INSERTING into C##AMALL.ADMIN_MEMBER
SET DEFINE OFF;
Insert into C##AMALL.ADMIN_MEMBER (ADMIN_ID,ADMIN_NAME,ADMIN_PWD,ADMIN_EMAIL,ADMIN_PHONE) values ('root','AMALL','admin','AMALL.COM','010-1111-1111');
REM INSERTING into C##AMALL.ASK
SET DEFINE OFF;
REM INSERTING into C##AMALL.CART
SET DEFINE OFF;
REM INSERTING into C##AMALL.CATEGORY
SET DEFINE OFF;
Insert into C##AMALL.CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (6,'기념일선물');
Insert into C##AMALL.CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (4,'식품');
Insert into C##AMALL.CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (1,'신발');
Insert into C##AMALL.CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (2,'잡화');
Insert into C##AMALL.CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (3,'커플티');
Insert into C##AMALL.CATEGORY (CATEGORY_ID,CATEGORY_NAME) values (5,'파티용품');
REM INSERTING into C##AMALL.MEMBER
SET DEFINE OFF;
REM INSERTING into C##AMALL.MYPAGE
SET DEFINE OFF;
REM INSERTING into C##AMALL.ORDERING
SET DEFINE OFF;
REM INSERTING into C##AMALL.ORDERINGREVIEW
SET DEFINE OFF;
REM INSERTING into C##AMALL.PRODUCT
SET DEFINE OFF;
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (13,'컴포즈 커플 팬츠','59DMFNBX',6000,3,'편안한 커플 바지','20210914',80,'잘 때 입기 좋은 편안한 커플 바지입니다.',null,null,null,1,0,'avon',3,'https://i.ibb.co/HVSvLJk/images.jpg','https://i.ibb.co/JcXcrdg/images-1.jpg','https://i.ibb.co/VHLXwVj/images-2.jpg',5000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (14,'오버팟 반잡업 맨투맨','PEWPAL8O',94700,24,'편안한 커플 카라 맨투맨','20190923',91,'잘 때 입기 좋은 편안한 커플 카라 맨투맨입니다.',null,null,null,4,0,'avon',3,'https://i.ibb.co/Z25n9Dg/1.jpg',null,null,5000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (15,'캐시미어 코트','OWNKSF72',98400,28,'따뜻한 코트','20200312',84,'추운날 입기 좋은 따뜻한 코트입니다.',null,null,null,5,0,'avon',3,'https://i.ibb.co/bFnPp8V/3.webp',null,null,0);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (16,'스니커즈 컨버스 커플 단화','HEQNT85R',12600,14,'커플 색상 스니커즈','20190905',67,'커플 색상 스니커즈입니다.',null,null,null,3,1,'avon',3,'https://i.ibb.co/nCWwrfZ/3.jpg',null,null,1000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (17,'에어 조던 로우','C1QTSDU4',47200,0,'남녀 구분없이 신는 로우 탑','20190809',86,'로우 탑 AJ1은 새로운 컬러와 텍스처로 클래식을 재해석하여 익숙하면서도 신선한 룩을 선사합니다. 최고로 사랑받는 신발에 모던한 멋을 더하는 프리미엄 소재와 포인트 디테일이 돋보입니다.',null,null,null,3,0,'avon',1,'https://i.ibb.co/02K1DpQ/1.png',null,null,5000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (18,'풍성한 장미 꽃다발','JNBPG15S',53100,17,'장미 생화로 만든 꽃다발','20210818',6,'당일 제품 준비해서 보내드립니다.',null,null,null,4,0,'avon',3,'https://i.ibb.co/ZGWyTQd/10.jpg',null,null,1000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (19,'구찌 마이콘 반지 블랙','NQQWLVQQ',43000,16,'명품 반지','20190507',5,'명품인척하는 반지입니다.',null,null,null,4,0,'enersys',2,'https://i.ibb.co/y4BksSp/44.jpg',null,null,4000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (20,'천연소가죽 장지갑','D0O95KBP',42800,0,'천연 소가죽으로 만든 지갑','20211120',15,'튼튼하고 좋은 선물용 지갑입니다.',null,null,null,4,0,'enersys',2,'https://i.ibb.co/dQP4hv2/55.jpg',null,null,0);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (21,'블랙 그레인 3단 지갑','R8ZB92UP',83900,8,'명품 지갑','20190726',5,'명품 단지갑입니다.',null,null,null,1,1,'enersys',2,'https://i.ibb.co/VMqXkm3/4.jpg',null,null,3000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (22,'초콜렛 세트','CWSGC5RT',49500,17,'기념일 초콜렛 세트','20210622',57,'수입산 초콜릿입니다.',null,null,null,4,0,'nestle',4,'https://i.ibb.co/wJZy2db/c.jpg',null,null,2000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (23,'초콜렛 세트 2','D1GB3UYG',69100,14,'종합 초콜렛','20201203',33,'달달한 국내산 수제 초콜렛입니다..',null,null,null,1,0,'nestle',4,'https://i.ibb.co/nCgzkjP/4.jpg',null,null,4000);
Insert into C##AMALL.PRODUCT (PROD_NUM,PROD_NAME,PROD_CODE,PROD_PRICE,PROD_STOCK,PROD_EXPLANATION,PROD_REGDATE,PROD_HIT,PROD_DETAIL,PROD_VAL1,PROD_VAL2,PROD_VAL3,PROD_STAR,PROD_SHOW,SELLER_ID,CATEGORY_ID,PROD_IMAGE1,PROD_IMAGE2,PROD_IMAGE3,PROD_DELIVERYFEE) values (24,'롤리팝 사탕','M3HSKPK7',73800,25,'롤리팝 막대 사탕','20200613',51,'어린 친구들을 위한 선물입니다.',null,null,null,3,1,'nestle',4,'https://i.ibb.co/mXksNgp/5.jpg',null,null,3000);
REM INSERTING into C##AMALL.QNA
SET DEFINE OFF;
REM INSERTING into C##AMALL.RECIEVEREVIEW
SET DEFINE OFF;
REM INSERTING into C##AMALL.SELLER
SET DEFINE OFF;
Insert into C##AMALL.SELLER (SELLER_ID,SELLER_PWD,SELLER_NICKNAME,SELLER_INTRO,SELLER_REVENUE,SELLER_IMAGE) values ('avon','avon','(주)에이본','Avon Products. 미국의 화장품, 향수 회사.',147262200,'https://i.ibb.co/PjdwCGS/AVON.png');
Insert into C##AMALL.SELLER (SELLER_ID,SELLER_PWD,SELLER_NICKNAME,SELLER_INTRO,SELLER_REVENUE,SELLER_IMAGE) values ('enersys','enersys','에너시스','악세사리를 전문으로 판매하는 기업',121043900,'https://i.ibb.co/rbrTjPx/MTBC.png');
Insert into C##AMALL.SELLER (SELLER_ID,SELLER_PWD,SELLER_NICKNAME,SELLER_INTRO,SELLER_REVENUE,SELLER_IMAGE) values ('mtbc','mtbc','MTBC','기념일 옷을 전문적으로 제작하고 유통하는 회사',108876100,'https://ibb.co/vsngF53');
Insert into C##AMALL.SELLER (SELLER_ID,SELLER_PWD,SELLER_NICKNAME,SELLER_INTRO,SELLER_REVENUE,SELLER_IMAGE) values ('nestle','nestle','롯데네슬레','스위스에 본사를 두고 있는 1위 식품기업',512248000,'https://i.ibb.co/p12Q9yW/NESTLE.png');
REM INSERTING into C##AMALL.WISHLIST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ADMIN_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ADMIN_MEMBER" ON "C##AMALL"."ADMIN_MEMBER" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ASK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ASK" ON "C##AMALL"."ASK" ("ASK_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_CART" ON "C##AMALL"."CART" ("CART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MYPAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_MYPAGE" ON "C##AMALL"."MYPAGE" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDERING
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ORDERING" ON "C##AMALL"."ORDERING" ("ORDERING_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDERINGREVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ORDERINGREVIEW" ON "C##AMALL"."ORDERINGREVIEW" ("ORDERING_REVIEW_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_PRODUCT" ON "C##AMALL"."PRODUCT" ("PROD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_QNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_QNA" ON "C##AMALL"."QNA" ("QNA_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECIEVEREVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_RECIEVEREVIEW" ON "C##AMALL"."RECIEVEREVIEW" ("RECIEVE_REVIEW_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SELLER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_SELLER" ON "C##AMALL"."SELLER" ("SELLER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_WISHLIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_WISHLIST" ON "C##AMALL"."WISHLIST" ("WISHLIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010567
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010567" ON "C##AMALL"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010568
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010568" ON "C##AMALL"."CATEGORY" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010632
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010632" ON "C##AMALL"."SELLER" ("SELLER_NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010696
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010696" ON "C##AMALL"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010697
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010697" ON "C##AMALL"."MEMBER" ("MEMBER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010698
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010698" ON "C##AMALL"."MEMBER" ("MEMBER_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010699
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010699" ON "C##AMALL"."MEMBER" ("MEMBER_HASH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010700
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010700" ON "C##AMALL"."MEMBER" ("MEMBER_MATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADMIN_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ADMIN_MEMBER" ON "C##AMALL"."ADMIN_MEMBER" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ASK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ASK" ON "C##AMALL"."ASK" ("ASK_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CART
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_CART" ON "C##AMALL"."CART" ("CART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010567
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010567" ON "C##AMALL"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010568
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010568" ON "C##AMALL"."CATEGORY" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010696
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010696" ON "C##AMALL"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010697
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010697" ON "C##AMALL"."MEMBER" ("MEMBER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010698
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010698" ON "C##AMALL"."MEMBER" ("MEMBER_PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010699
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010699" ON "C##AMALL"."MEMBER" ("MEMBER_HASH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010700
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010700" ON "C##AMALL"."MEMBER" ("MEMBER_MATCH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MYPAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_MYPAGE" ON "C##AMALL"."MYPAGE" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDERING
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ORDERING" ON "C##AMALL"."ORDERING" ("ORDERING_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDERINGREVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_ORDERINGREVIEW" ON "C##AMALL"."ORDERINGREVIEW" ("ORDERING_REVIEW_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_PRODUCT" ON "C##AMALL"."PRODUCT" ("PROD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_QNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_QNA" ON "C##AMALL"."QNA" ("QNA_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RECIEVEREVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_RECIEVEREVIEW" ON "C##AMALL"."RECIEVEREVIEW" ("RECIEVE_REVIEW_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010632
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."SYS_C0010632" ON "C##AMALL"."SELLER" ("SELLER_NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SELLER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_SELLER" ON "C##AMALL"."SELLER" ("SELLER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_WISHLIST
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##AMALL"."PK_WISHLIST" ON "C##AMALL"."WISHLIST" ("WISHLIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_MEMBER
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."ADMIN_MEMBER" ADD CONSTRAINT "PK_ADMIN_MEMBER" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."ADMIN_MEMBER" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ADMIN_MEMBER" MODIFY ("ADMIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ADMIN_MEMBER" MODIFY ("ADMIN_PWD" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ADMIN_MEMBER" MODIFY ("ADMIN_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ADMIN_MEMBER" MODIFY ("ADMIN_PHONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASK
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."ASK" MODIFY ("ASK_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ASK" MODIFY ("ASK_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ASK" MODIFY ("ASK_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ASK" MODIFY ("ASK_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ASK" MODIFY ("ASK_REPLYEXIST" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ASK" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ASK" ADD CONSTRAINT "PK_ASK" PRIMARY KEY ("ASK_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."CART" ADD CONSTRAINT "PK_CART" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."CART" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CART" MODIFY ("CART_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CART" MODIFY ("CART_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CART" MODIFY ("CART_RESULT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CART" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CART" MODIFY ("PROD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."CATEGORY" ADD UNIQUE ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."CATEGORY" ADD UNIQUE ("CATEGORY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_PWD" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_SEX" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_CONNECT_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_HASH" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_POST_CODE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" MODIFY ("MEMBER_DETAIL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MEMBER" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."MEMBER" ADD UNIQUE ("MEMBER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."MEMBER" ADD UNIQUE ("MEMBER_PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."MEMBER" ADD UNIQUE ("MEMBER_HASH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 167 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."MEMBER" ADD UNIQUE ("MEMBER_MATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MYPAGE
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."MYPAGE" ADD CONSTRAINT "PK_MYPAGE" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."MYPAGE" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MYPAGE" MODIFY ("MEMBER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MYPAGE" MODIFY ("MEMBER_YN" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MYPAGE" MODIFY ("MATCH_YN" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."MYPAGE" MODIFY ("QNA_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERING
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."ORDERING" ADD CONSTRAINT "PK_ORDERING" PRIMARY KEY ("ORDERING_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_NAME1" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_PHONE1" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_CARD" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("ORDERING_RESULT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERING" MODIFY ("SELLER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERINGREVIEW
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_REVIEW_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_REVIEW_SHOW" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" ADD CONSTRAINT "PK_ORDERINGREVIEW" PRIMARY KEY ("ORDERING_REVIEW_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_REVIEW_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_REVIEW_WRITER" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_REVIEW_PWD" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" MODIFY ("ORDERING_REVIEW_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY ("PROD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_CODE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_STOCK" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_EXPLANATION" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_HIT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_STAR" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("PROD_SHOW" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("SELLER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."PRODUCT" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("QNA_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("QNA_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("QNA_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("QNA_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("QNA_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("QNA_REPLYEXIST" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."QNA" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECIEVEREVIEW
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("RECIEVE_REVIEW_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("ORDERING_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("RECIEVE_REVIEW_WRITER" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("RECIEVE_REVIEW_PWD" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("RECIEVE_REVIEW_TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" MODIFY ("RECIEVE_REVIEW_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" ADD CONSTRAINT "PK_RECIEVEREVIEW" PRIMARY KEY ("RECIEVE_REVIEW_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."SELLER" MODIFY ("SELLER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."SELLER" MODIFY ("SELLER_PWD" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."SELLER" MODIFY ("SELLER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."SELLER" MODIFY ("SELLER_INTRO" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."SELLER" MODIFY ("SELLER_REVENUE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."SELLER" ADD UNIQUE ("SELLER_NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##AMALL"."SELLER" ADD CONSTRAINT "PK_SELLER" PRIMARY KEY ("SELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WISHLIST
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."WISHLIST" MODIFY ("WISHLIST_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."WISHLIST" MODIFY ("WISHLIST_SHOW" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."WISHLIST" MODIFY ("WISHLIST_REGDATE" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."WISHLIST" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."WISHLIST" MODIFY ("PROD_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##AMALL"."WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY ("WISHLIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."CART" ADD CONSTRAINT "FK_PRODUCT_TO_CART_1" FOREIGN KEY ("PROD_NUM")
	  REFERENCES "C##AMALL"."PRODUCT" ("PROD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MYPAGE
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."MYPAGE" ADD CONSTRAINT "FK_RECIEVEREVIEW_TO_MYPAGE_1" FOREIGN KEY ("RECIEVE_REVIEW_NUM")
	  REFERENCES "C##AMALL"."RECIEVEREVIEW" ("RECIEVE_REVIEW_NUM") ENABLE;
  ALTER TABLE "C##AMALL"."MYPAGE" ADD CONSTRAINT "FK_ORDERINGREVIEW_TO_MYPAGE_1" FOREIGN KEY ("ORDERING_REVIEW_NUM")
	  REFERENCES "C##AMALL"."ORDERINGREVIEW" ("ORDERING_REVIEW_NUM") ENABLE;
  ALTER TABLE "C##AMALL"."MYPAGE" ADD CONSTRAINT "FK_QNA_TO_MYPAGE_1" FOREIGN KEY ("QNA_NUM")
	  REFERENCES "C##AMALL"."QNA" ("QNA_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERING
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."ORDERING" ADD CONSTRAINT "FK_PRODUCT_TO_ORDERING_1" FOREIGN KEY ("PROD_NUM")
	  REFERENCES "C##AMALL"."PRODUCT" ("PROD_NUM") ENABLE;
  ALTER TABLE "C##AMALL"."ORDERING" ADD CONSTRAINT "FK_CART_TO_ORDERING_1" FOREIGN KEY ("CART_ID")
	  REFERENCES "C##AMALL"."CART" ("CART_ID") ENABLE;
  ALTER TABLE "C##AMALL"."ORDERING" ADD CONSTRAINT "FK_SELLER_TO_ORDERING_1" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "C##AMALL"."SELLER" ("SELLER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERINGREVIEW
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" ADD CONSTRAINT "FK_PRODUCT_TO_ORDERINGREVIEW_1" FOREIGN KEY ("PROD_NUM")
	  REFERENCES "C##AMALL"."PRODUCT" ("PROD_NUM") ENABLE;
  ALTER TABLE "C##AMALL"."ORDERINGREVIEW" ADD CONSTRAINT "FK_ORDERING_TO_ORDERINGREVIEW_1" FOREIGN KEY ("ORDERING_NUM")
	  REFERENCES "C##AMALL"."ORDERING" ("ORDERING_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."PRODUCT" ADD CONSTRAINT "FK_SELLER_TO_PRODUCT_1" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "C##AMALL"."SELLER" ("SELLER_ID") ENABLE;
  ALTER TABLE "C##AMALL"."PRODUCT" ADD CONSTRAINT "FK_CATEGORY_TO_PRODUCT_1" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "C##AMALL"."CATEGORY" ("CATEGORY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."QNA" ADD CONSTRAINT "FK_PRODUCT_TO_QNA_1" FOREIGN KEY ("PROD_NUM")
	  REFERENCES "C##AMALL"."PRODUCT" ("PROD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECIEVEREVIEW
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" ADD CONSTRAINT "FK_ORDERING_TO_RECIEVEREVIEW_1" FOREIGN KEY ("ORDERING_NUM")
	  REFERENCES "C##AMALL"."ORDERING" ("ORDERING_NUM") ENABLE;
  ALTER TABLE "C##AMALL"."RECIEVEREVIEW" ADD CONSTRAINT "FK_PRODUCT_TO_RECIEVEREVIEW_1" FOREIGN KEY ("PROD_NUM")
	  REFERENCES "C##AMALL"."PRODUCT" ("PROD_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WISHLIST
--------------------------------------------------------

  ALTER TABLE "C##AMALL"."WISHLIST" ADD CONSTRAINT "FK_PRODUCT_TO_WISHLIST_1" FOREIGN KEY ("PROD_NUM")
	  REFERENCES "C##AMALL"."PRODUCT" ("PROD_NUM") ENABLE;
