-- ============================================
-- Amall 선물 기능 DB 스키마 확장
-- ============================================

-- 1. CART 테이블에 선물 관련 컬럼 추가
ALTER TABLE CART ADD (
    IS_GIFT CHAR(1) DEFAULT 'N' NOT NULL,          -- 선물 여부 ('Y' or 'N')
    GIFT_TO_MEMBER_ID VARCHAR2(50),                -- 선물 받는 사람 ID (매칭된 상대방)
    GIFT_MESSAGE VARCHAR2(500),                     -- 선물 메시지 ("생일 축하해!")
    CONSTRAINT CHK_CART_IS_GIFT CHECK (IS_GIFT IN ('Y', 'N'))
);

-- 인덱스 추가 (성능 향상)
CREATE INDEX IDX_CART_GIFT_TO ON CART(GIFT_TO_MEMBER_ID) WHERE IS_GIFT = 'Y';

-- 2. WISHLIST 테이블 확인 (이미 존재하는 구조)
-- WISHLIST_ID, WISHLIST_REGDATE, MEMBER_ID, PROD_NUM

-- 3. ORDER 테이블 생성 (주문 기능)
CREATE TABLE ORDERS (
    ORDER_ID VARCHAR2(50) PRIMARY KEY,              -- 주문 번호
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,       -- 주문 일시
    ORDER_STATUS VARCHAR2(20) DEFAULT 'PENDING',    -- 주문 상태 (PENDING, PAID, SHIPPED, DELIVERED, CANCELLED)
    MEMBER_ID VARCHAR2(50) NOT NULL,                -- 주문자 ID

    -- 배송 정보
    DELIVERY_NAME VARCHAR2(50) NOT NULL,            -- 받는 사람 이름
    DELIVERY_PHONE VARCHAR2(20) NOT NULL,           -- 받는 사람 전화번호
    DELIVERY_POST_CODE VARCHAR2(10) NOT NULL,       -- 우편번호
    DELIVERY_ADDRESS VARCHAR2(200) NOT NULL,        -- 주소
    DELIVERY_DETAIL_ADDRESS VARCHAR2(200),          -- 상세주소
    DELIVERY_MESSAGE VARCHAR2(200),                 -- 배송 메시지

    -- 결제 정보
    TOTAL_AMOUNT NUMBER(10) DEFAULT 0 NOT NULL,     -- 총 금액
    DELIVERY_FEE NUMBER(10) DEFAULT 0,              -- 배송비
    PAYMENT_METHOD VARCHAR2(20),                    -- 결제 방법

    -- 선물 정보
    IS_GIFT CHAR(1) DEFAULT 'N',                    -- 선물 여부
    GIFT_FROM_MEMBER_ID VARCHAR2(50),               -- 선물 보낸 사람
    GIFT_MESSAGE VARCHAR2(500),                     -- 선물 메시지

    CONSTRAINT FK_ORDERS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CHK_ORDER_STATUS CHECK (ORDER_STATUS IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT CHK_ORDER_IS_GIFT CHECK (IS_GIFT IN ('Y', 'N'))
);

-- 4. ORDER_ITEM 테이블 생성 (주문 상세)
CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID NUMBER PRIMARY KEY,
    ORDER_ID VARCHAR2(50) NOT NULL,
    PROD_NUM NUMBER NOT NULL,
    PROD_NAME VARCHAR2(200),                        -- 주문 시점의 상품명 (히스토리)
    PROD_PRICE NUMBER(10),                          -- 주문 시점의 가격 (히스토리)
    QUANTITY NUMBER(5) NOT NULL,

    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PROD_NUM) REFERENCES PRODUCT(PROD_NUM)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_ORDER_ITEM START WITH 1 INCREMENT BY 1;

-- 5. 선물 알림 테이블 (선물 배송지 입력 요청)
CREATE TABLE GIFT_DELIVERY_REQUEST (
    REQUEST_ID NUMBER PRIMARY KEY,
    ORDER_ID VARCHAR2(50) NOT NULL,                 -- 주문 ID
    TO_MEMBER_ID VARCHAR2(50) NOT NULL,             -- 선물 받는 사람
    FROM_MEMBER_ID VARCHAR2(50) NOT NULL,           -- 선물 보낸 사람
    GIFT_MESSAGE VARCHAR2(500),                     -- 선물 메시지
    REQUEST_STATUS VARCHAR2(20) DEFAULT 'PENDING',  -- 상태 (PENDING, COMPLETED)
    CREATED_DATE DATE DEFAULT SYSDATE,
    COMPLETED_DATE DATE,

    CONSTRAINT FK_GIFT_REQ_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_GIFT_REQ_TO FOREIGN KEY (TO_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT FK_GIFT_REQ_FROM FOREIGN KEY (FROM_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    CONSTRAINT CHK_GIFT_REQ_STATUS CHECK (REQUEST_STATUS IN ('PENDING', 'COMPLETED'))
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_GIFT_DELIVERY_REQUEST START WITH 1 INCREMENT BY 1;

-- 인덱스 생성
CREATE INDEX IDX_GIFT_REQ_TO_MEMBER ON GIFT_DELIVERY_REQUEST(TO_MEMBER_ID, REQUEST_STATUS);
CREATE INDEX IDX_ORDERS_MEMBER ON ORDERS(MEMBER_ID);
CREATE INDEX IDX_ORDER_ITEM_ORDER ON ORDER_ITEM(ORDER_ID);

-- ============================================
-- 샘플 데이터 (테스트용)
-- ============================================

-- 예시: 일반 장바구니
INSERT INTO CART (CART_ID, CART_QUANTITY, CART_REG_DATE, MEMBER_ID, PROD_NUM, IS_GIFT)
VALUES (1, 2, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'user1', 101, 'N');

-- 예시: 선물 장바구니
INSERT INTO CART (CART_ID, CART_QUANTITY, CART_REG_DATE, MEMBER_ID, PROD_NUM, IS_GIFT, GIFT_TO_MEMBER_ID, GIFT_MESSAGE)
VALUES (2, 1, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI'), 'user1', 102, 'Y', 'user2', '생일 축하해!');

COMMIT;

-- ============================================
-- 롤백용 (필요 시)
-- ============================================

/*
-- CART 테이블 컬럼 삭제
ALTER TABLE CART DROP COLUMN IS_GIFT;
ALTER TABLE CART DROP COLUMN GIFT_TO_MEMBER_ID;
ALTER TABLE CART DROP COLUMN GIFT_MESSAGE;

-- 테이블 삭제
DROP TABLE GIFT_DELIVERY_REQUEST;
DROP TABLE ORDER_ITEM;
DROP TABLE ORDERS;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_ORDER_ITEM;
DROP SEQUENCE SEQ_GIFT_DELIVERY_REQUEST;
*/
